---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  indentation:
    indent-sequences: consistent
    spaces: 2
  line-length: disable
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1

ignore: |
  testdata/caches/
  tmp/
