name: Release binary builder
on:
  release:
    types: [published]
permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write
jobs:
  releases-matrix:
    name: ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: amd64
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: darwin
            goarch: amd64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - uses: wangyoucao577/go-release-action@v1.55
        id: go_release
        with:
          goversion: go.mod
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goarm: ${{ matrix.goarm }}
          binary_name: dependabot
          project_path: cmd/dependabot
          ldflags: -X github.com/dependabot/cli/cmd/dependabot/internal/cmd.version=${{ github.event.release.tag_name }}
      - uses: actions/attest-build-provenance@v4
        with:
          subject-path: ${{ steps.go_release.outputs.release_asset_dir }}/*
