name: Scorecard analysis

on: # yamllint disable-line rule:truthy
  push:
    branches: [ "main" ]
  schedule:
    - cron: '22 17 * * 1'
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8e # v4.3.0
        with:
          persist-credentials: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@4ed4131f56e31d3a9b3f6dba4c0d13e0951d9a # v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@49c5498669e3d9b1e47c6f8ad2a8f305c9cc014d # v3.29.5
        with:
          sarif_file: results.sarif
