mkdir -p .github/workflows
cat << 'EOF' > .github/workflows/smoke.yml
name: Smoke

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  suites:
    runs-on: ubuntu-latest
    steps:
      - id: gather
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          URL="https://api.github.com/repos/dependabot/smoke-tests/contents/tests"
          DATA="$(gh api $URL | jq -r '.[].name' | sed 's/smoke-//' | sed 's/\.yaml$//' | jq -R . | jq -sc .)"
          echo "suite=$DATA" >> $GITHUB_OUTPUT
    outputs:
      suites: ${{ steps.gather.outputs.suite }}

  smoke:
    needs: suites
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ json(needs.suites.outputs.suites) }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Smoke Test
        run: |
          echo "Running smoke test for ${{ matrix.suite }}"
EOF
